name: epiworkshop

services:
  nextstrain:
    container_name: nextstrain
    image: nextstrain/base@sha256:ea546afb4a1400691be1a3a44adb4e1621346d006b7f5c02f86182abfa5245f3
  jupyter:
    container_name: jupyter
    build: 
      context: .
      dockerfile: jupyter.Dockerfile
    ports:
      - 8888:8888
    volumes:
      - type: bind
        source: .
        target: /home/jovyan
    command: "start-notebook.sh \
              --no-browser"
    tty: true
